# Generated by Django 4.2.2 on 2023-07-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('species', models.CharField(max_length=200, verbose_name='Species')),
                ('gender', models.CharField(max_length=200, verbose_name='Gender')),
                ('image', models.URLField(verbose_name='URL Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
